
from autogen import ConversableAgent
from autogen.coding import LocalCommandLineCodeExecutor

import os
from agents.prompts.thought_agent.coder_agent import working_dir

# Default executor (for backward compatibility)
executor = LocalCommandLineCodeExecutor(
    timeout=120,  # Timeout for each code execution in seconds.
    work_dir=working_dir,  # Use the working directory to store the code files.
)

system_message = """You are the Code Execution Agent.  
Your role is to execute Python code snippets and return the output.  
Always execute code provided in ```python blocks.  
This should be called after the `coder_agent` or any agent generates Python code.  
Return results clearly and only after successful execution.
"""

description = """
code_executor_agent Executes Python code generated by other agents (always after `coder_agent`). Triggered whenever a message contains code in ```python blocks, and returns the execution output. This has access to code executor and can actually execute code and returns output
"""

def get_code_executor_agent_config(custom_working_dir=None):
    """
    Get code executor agent configuration with optional custom working directory.
    
    Args:
        custom_working_dir: Optional custom working directory path
    
    Returns:
        dict: Code executor agent configuration
    """
    work_dir = custom_working_dir if custom_working_dir else working_dir
    os.makedirs(work_dir, exist_ok=True)
    
    custom_executor = LocalCommandLineCodeExecutor(
        timeout=120,
        work_dir=work_dir,
    )
    
    return {
        "type": "conversable",
        "name": "code_executor_agent",
        "system_message": system_message,
        "description": description,
        "llm_config": False,
        "code_execution_config": {"executor": custom_executor},
        "human_input_mode": "NEVER",
    }

# Default configuration (for backward compatibility)
code_executor_agent = {
    "type": "conversable",
    "name": "code_executor_agent",
    "system_message": system_message,
    "description": description,
    "llm_config": False,
    "code_execution_config": {"executor": executor},
    "human_input_mode": "NEVER",
}