
from autogen import ConversableAgent
from autogen.coding import LocalCommandLineCodeExecutor

import os
from agents.prompts.thought_agent.coder_agent import working_dir

executor = LocalCommandLineCodeExecutor(
    timeout=10,  # Timeout for each code execution in seconds.
    work_dir=working_dir,  # Use the working directory to store the code files.
)


# system_message = """
# Execute the required code snippets.
# """

system_message = """You are the Code Execution Agent.  
Your role is to execute Python code snippets and return the output.  
Always execute code provided in ```python blocks.  
This should be called after the `coder_agent` or any agent generates Python code.  
Return results clearly and only after successful execution.
"""

# description = """
# It executes code and returns the output. Always call this for executing code whenever there is code in any message to get the output.
# """

description = """
code_executor_agent Executes Python code generated by other agents (always after `coder_agent`). Triggered whenever a message contains code in ```python blocks, and returns the execution output. This has access to code executor and can actually execute code and returns output
"""

# # Create an agent with code executor configuration.
# code_executor_agent = ConversableAgent(
#     "code_executor_agent",
#     description=description,
#     llm_config=False,  # Turn off LLM for this agent.
#     code_execution_config={"executor": executor},  # Use the local command line code executor.
#     human_input_mode="ALWAYS",  # Always take human input for this agent for safety.
# )

code_executor_agent = {
    "type": "conversable",
    "name": "code_executor_agent",
    "system_message": system_message,
    "description": description,
    "llm_config": False,
    "code_execution_config": {"executor": executor},
    "human_input_mode": "NEVER",
}